#!/bin/sh

riverctl map normal Super       Q      close
riverctl map normal Alt         F4     close
riverctl map normal Super+Shift Q      exit
riverctl map normal Super       Z      zoom
riverctl map normal Super       E      toggle-fullscreen
riverctl map normal Super       N      focus-view     next
riverctl map normal Super       P      focus-view     previous
riverctl map normal Super       period focus-output   next
riverctl map normal Super       comma  focus-output   previous
riverctl map normal Super+Shift period send-to-output next
riverctl map normal Super+Shift comma  send-to-output previous

riverctl map normal Super       Return spawn 'alacritty'
riverctl map normal Super+Shift F      spawn 'bemenu-run --prompt "Run Binary"'
riverctl map normal Super       L      spawn 'loginctl lock-session'
riverctl map normal None        Print  spawn 'grim -g "$(slurp)" - | swappy -f -'
riverctl map normal Super       H      spawn 'alacritty -e man pta-desktop-environment'
riverctl map normal Super       F      spawn 'j4-dmenu-desktop --display-binary --no-generic --term=alacritty "--dmenu=bemenu --prompt \"Run Application\""'

riverctl map-pointer normal Super BTN_LEFT   move-view
riverctl map-pointer normal Super BTN_RIGHT  resize-view
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

for i in $(seq 1 9)
do
  tags=$((1 << ($i - 1)))
  riverctl map normal Super               $i set-focused-tags    $tags
  riverctl map normal Super+Shift         $i set-view-tags       $tags
  riverctl map normal Super+Control       $i toggle-focused-tags $tags
  riverctl map normal Super+Shift+Control $i toggle-view-tags    $tags
done

all_tags=$(((1 << 9) - 1))
riverctl map normal Super       0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags    $all_tags

for mode in normal locked
do
  riverctl map $mode None XF86AudioRaiseVolume  spawn 'pamixer -i 5'
  riverctl map $mode None XF86AudioLowerVolume  spawn 'pamixer -d 5'
  riverctl map $mode None XF86AudioMute         spawn 'pamixer --toggle-mute'

  riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
  riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
done

riverctl background-color       0x000000
riverctl border-color-focused   0xf58017
riverctl border-color-unfocused 0x808080
riverctl border-color-urgent    0x4c4c4c
riverctl set-repeat             25 600

export XCURSOR_THEME=Adwaita
export XCURSOR_SIZE=24
riverctl xcursor-theme "$XCURSOR_THEME" "$XCURSOR_SIZE"

riverctl default-layout rivertile
rivertile -main-ratio 0.5 &

source "$XDG_CONFIG_HOME/river/init"

yambar &
swww-daemon &
swayidle -w &
kanshi &
dunst &
thunar --daemon &
dex --autostart &
